//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLPServiceEndpoint.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3lEhKRZ853aqZE_S4-02Mr6mNvxgJaJrgos6SQuv3x3C")]
        public string ibm_api_key {
            get {
                return ((string)(this["ibm_api_key"]));
            }
            set {
                this["ibm_api_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.eu-de.natural-language-understanding.watson.cloud.ibm.com/instances/e" +
            "c45c75e-8c71-4289-abe9-7964f407f255")]
        public string ibm_service_url {
            get {
                return ((string)(this["ibm_service_url"]));
            }
            set {
                this["ibm_service_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Bachelor_Pallas\\Bachelor - Code\\Google\\My First Project-2361c4158265.json")]
        public string google_api_path {
            get {
                return ((string)(this["google_api_path"]));
            }
            set {
                this["google_api_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1e4a7cfdf9ff400892566d3b0f72b3fc")]
        public string microsoft_api_key {
            get {
                return ((string)(this["microsoft_api_key"]));
            }
            set {
                this["microsoft_api_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ms-freetrial-textanalysis.cognitiveservices.azure.com/")]
        public string microsoft_endpoint {
            get {
                return ((string)(this["microsoft_endpoint"]));
            }
            set {
                this["microsoft_endpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("germanywestcentral")]
        public string microsoft_standort {
            get {
                return ((string)(this["microsoft_standort"]));
            }
            set {
                this["microsoft_standort"] = value;
            }
        }
    }
}
